export {
  GoalId,
  GoalStatus,
  StepId,
  StepStatus,
  EvidenceId,
  EvidenceType,
  TEXT_EVIDENCE_PREFIX,
  BadgeId,
  UserSettingsId,
  Schema,
} from "./schema";
export { evolu, useAppEvolu, EvoluAppProvider } from "./evolu";
export {
  // Goal
  goalsQuery,
  activeGoalsQuery,
  stepsForActiveGoalsQuery,
  createGoal,
  updateGoal,
  completeGoal,
  uncompleteGoal,
  deleteGoal,
  // Step
  stepsByGoalQuery,
  isPendingStep,
  findFirstPendingIndex,
  createStep,
  updateStep,
  canCompleteStep,
  completeStep,
  uncompleteStep,
  deleteStep,
  reorderSteps,
  // Evidence gating
  canCompleteGoal,
  // Evidence
  evidenceByGoalQuery,
  evidenceByStepQuery,
  stepEvidenceByGoalQuery,
  createEvidence,
  updateEvidence,
  deleteEvidence,
  // Badge
  badgesQuery,
  badgeByGoalQuery,
  badgeByIdQuery,
  badgeWithGoalQuery,
  badgesWithGoalsQuery,
  createBadge,
  updateBadge,
  deleteBadge,
  // UserSettings
  userSettingsQuery,
  createUserSettings,
  updateUserSettings,
  updateUserSettingsKey,
  clearUserSettingsKey,
  markWelcomeSeen,
} from "./queries";
