window.THEME_FIXES = [
  {
    "id": "light-default",
    "theme": "Full Ride",
    "pair": "primary button",
    "bgVar": "--ob-action-primary-bg",
    "fgVar": "--ob-action-primary-fg",
    "curFg": "#fafafa",
    "curBg": "#3b82f6",
    "curRatio": 3.52,
    "newBg": "#326fd1",
    "newRatio": 4.67
  },
  {
    "id": "light-default",
    "theme": "Full Ride",
    "pair": "success",
    "bgVar": "--ob-success",
    "fgVar": "--ob-success-foreground",
    "curFg": "#fafafa",
    "curBg": "#059669",
    "curRatio": 3.61,
    "newBg": "#048059",
    "newRatio": 4.78
  },
  {
    "id": "dark-default",
    "theme": "Night",
    "pair": "success",
    "bgVar": "--ob-success",
    "fgVar": "--ob-success-foreground",
    "curFg": "#fafafa",
    "curBg": "#34d399",
    "curRatio": 1.84,
    "newBg": "#1f7f5c",
    "newRatio": 4.76
  },
  {
    "id": "dark-default",
    "theme": "Night",
    "pair": "info",
    "bgVar": "--ob-info",
    "fgVar": "--ob-info-foreground",
    "curFg": "#fafafa",
    "curBg": "#60a5fa",
    "curRatio": 2.44,
    "newBg": "#4374af",
    "newRatio": 4.64
  },
  {
    "id": "light-highContrast",
    "theme": "Bold Ink",
    "pair": "destructive",
    "bgVar": "--ob-action-destructive-bg",
    "fgVar": "--ob-action-destructive-fg",
    "curFg": "#ffffff",
    "curBg": "#cc5500",
    "curRatio": 4.31,
    "newBg": "#c25100",
    "newRatio": 4.71
  },
  {
    "id": "light-highContrast",
    "theme": "Bold Ink",
    "pair": "success",
    "bgVar": "--ob-success",
    "fgVar": "--ob-success-foreground",
    "curFg": "#fafafa",
    "curBg": "#008866",
    "curRatio": 4.27,
    "newBg": "#008161",
    "newRatio": 4.65
  },
  {
    "id": "light-highContrast",
    "theme": "Bold Ink",
    "pair": "warning",
    "bgVar": "--ob-warning",
    "fgVar": "--ob-warning-foreground",
    "curFg": "#262626",
    "curBg": "#cc5500",
    "curRatio": 3.51,
    "newBg": "#d67733",
    "newRatio": 4.72
  },
  {
    "id": "light-dyslexia",
    "theme": "Warm",
    "pair": "primary button",
    "bgVar": "--ob-action-primary-bg",
    "fgVar": "--ob-action-primary-fg",
    "curFg": "#fafafa",
    "curBg": "#4e7d9e",
    "curRatio": 4.23,
    "newBg": "#4a7796",
    "newRatio": 4.61
  },
  {
    "id": "light-dyslexia",
    "theme": "Warm",
    "pair": "destructive",
    "bgVar": "--ob-action-destructive-bg",
    "fgVar": "--ob-action-destructive-fg",
    "curFg": "#333333",
    "curBg": "#b5913a",
    "curRatio": 4.26,
    "newBg": "#bb9949",
    "newRatio": 4.67
  },
  {
    "id": "light-dyslexia",
    "theme": "Warm",
    "pair": "success",
    "bgVar": "--ob-success",
    "fgVar": "--ob-success-foreground",
    "curFg": "#fafafa",
    "curBg": "#4a8a62",
    "curRatio": 3.94,
    "newBg": "#437c58",
    "newRatio": 4.71
  },
  {
    "id": "light-dyslexia",
    "theme": "Warm",
    "pair": "highlight",
    "bgVar": "--ob-highlight",
    "fgVar": "--ob-highlight-foreground",
    "curFg": "#ffffff",
    "curBg": "#4e7d9e",
    "curRatio": 4.42,
    "newBg": "#4c7a9a",
    "newRatio": 4.61
  },
  {
    "id": "light-autismFriendly",
    "theme": "Still",
    "pair": "destructive",
    "bgVar": "--ob-action-destructive-bg",
    "fgVar": "--ob-action-destructive-fg",
    "curFg": "#333333",
    "curBg": "#8a7a5a",
    "curRatio": 3.02,
    "newBg": "#a79b83",
    "newRatio": 4.62
  },
  {
    "id": "light-autismFriendly",
    "theme": "Still",
    "pair": "tab active",
    "bgVar": "--ob-chrome-tab-bar-bg",
    "fgVar": "--ob-chrome-tab-bar-active-fg",
    "curFg": "#ffffff",
    "curBg": "#8a7a9a",
    "curRatio": 3.94,
    "newBg": "#7c6e8b",
    "newRatio": 4.72
  },
  {
    "id": "light-autismFriendly",
    "theme": "Still",
    "pair": "tab idle",
    "bgVar": "--ob-chrome-tab-bar-bg",
    "fgVar": "--ob-chrome-tab-bar-fg",
    "curFg": "#333333",
    "curBg": "#8a7a9a",
    "curRatio": 3.21,
    "newBg": "#a498b1",
    "newRatio": 4.64
  },
  {
    "id": "light-autismFriendly",
    "theme": "Still",
    "pair": "success",
    "bgVar": "--ob-success",
    "fgVar": "--ob-success-foreground",
    "curFg": "#fafafa",
    "curBg": "#059669",
    "curRatio": 3.61,
    "newBg": "#048059",
    "newRatio": 4.78
  },
  {
    "id": "light-lowVision",
    "theme": "Loud",
    "pair": "warning",
    "bgVar": "--ob-warning",
    "fgVar": "--ob-warning-foreground",
    "curFg": "#262626",
    "curBg": "#995500",
    "curRatio": 2.63,
    "newBg": "#b8884d",
    "newRatio": 4.8
  },
  {
    "id": "light-lowInfo",
    "theme": "Clean",
    "pair": "success",
    "bgVar": "--ob-success",
    "fgVar": "--ob-success-foreground",
    "curFg": "#fafafa",
    "curBg": "#059669",
    "curRatio": 3.61,
    "newBg": "#048059",
    "newRatio": 4.78
  }
];
